package test.model;

public class WmSysConfigKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WM_SYS_CONFIG.CONFIG_NAME
     *
     * @mbggenerated Tue Apr 12 16:16:13 CST 2016
     */
    private String configName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WM_SYS_CONFIG.CONFIG_NAME
     *
     * @return the value of WM_SYS_CONFIG.CONFIG_NAME
     *
     * @mbggenerated Tue Apr 12 16:16:13 CST 2016
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WM_SYS_CONFIG.CONFIG_NAME
     *
     * @param configName the value for WM_SYS_CONFIG.CONFIG_NAME
     *
     * @mbggenerated Tue Apr 12 16:16:13 CST 2016
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }
}