package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.WmSysConfig;
import test.model.WmSysConfigExample;
import test.model.WmSysConfigKey;

public interface WmSysConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Tue Apr 12 16:16:13 CST 2016
     */
    int countByExample(WmSysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Tue Apr 12 16:16:13 CST 2016
     */
    int deleteByExample(WmSysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Tue Apr 12 16:16:13 CST 2016
     */
    int deleteByPrimaryKey(WmSysConfigKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Tue Apr 12 16:16:13 CST 2016
     */
    int insert(WmSysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Tue Apr 12 16:16:13 CST 2016
     */
    int insertSelective(WmSysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Tue Apr 12 16:16:13 CST 2016
     */
    List<WmSysConfig> selectByExample(WmSysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Tue Apr 12 16:16:13 CST 2016
     */
    WmSysConfig selectByPrimaryKey(WmSysConfigKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Tue Apr 12 16:16:13 CST 2016
     */
    int updateByExampleSelective(@Param("record") WmSysConfig record, @Param("example") WmSysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Tue Apr 12 16:16:13 CST 2016
     */
    int updateByExample(@Param("record") WmSysConfig record, @Param("example") WmSysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Tue Apr 12 16:16:13 CST 2016
     */
    int updateByPrimaryKeySelective(WmSysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Tue Apr 12 16:16:13 CST 2016
     */
    int updateByPrimaryKey(WmSysConfig record);
}